### ISSUE TITLE
Acuminator makes Visual Studio 2017 crash periodically

### ISSUE THREAD

**Issue by aistosi** [Acumatica/Acuminator#202]
The following is displayed in the Event Viewer:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OperationCanceledException
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Acuminator.Analyzers.StaticAnalysis.DacExtensionDefaultAttribute.DacExtensionDefaultAttributeAnalyzer+<CheckDacPropertyAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Acuminator.Analyzers.StaticAnalysis.DacExtensionDefaultAttribute.DacExtensionDefaultAttributeAnalyzer+<>c__DisplayClass3_0+<<AnalyzeCompilation>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by SENya1990** [comment]
@aistosi Could you please write the version of the Visual Studio and the version of the Acuminator?

**Comment by aistosi** [comment]
Visual Studio version 15.4.4 and Acuminator version 1.5.0

**Comment by SENya1990** [comment]
@aistosi The Acuminator has been tested with the latest update version of the Visual Studio 2017. The latest available VS 2017 version is 15.9.9. Please update your Visual Studio and write again if the bug reappears
