### ISSUE TITLE
AD0001 shown for LocalizationInvocationAnalyzer

### ISSUE THREAD

**Issue by biggik** [Acumatica/Acuminator#263]
I'm getting multiple issues like the following. Full source of QueryHelpers.cs available upon request.

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Acuminator.Analyzers.StaticAnalysis.Localization.LocalizationInvocationAnalyzer' threw an exception of type 'System.OperationCanceledException' with message 'The operation was canceled.'.	CentaraRetail		1	Active	Analyzer 'Acuminator.Analyzers.StaticAnalysis.Localization.LocalizationInvocationAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: CentaraRetail
SyntaxTree: C:\dev\Temabit\acumaticaintegration\Customization\CentaraRetailProject\CentaraRetail\Helpers\QueryHelpers.cs
SyntaxNode: s.Substring(0, len) [InvocationExpressionSyntax]@[755..774) (28,23)-(28,42)

System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Acuminator.Analyzers.StaticAnalysis.Localization.LocalizationInvocationAnalyzer.AnalyzeLocalizationMethodInvocation(SyntaxNodeAnalysisContext syntaxContext, PXContext pxContext)
   at Acuminator.Analyzers.StaticAnalysis.Localization.LocalizationInvocationAnalyzer.<>c__DisplayClass13_0.<AnalyzeCompilation>b__0(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

**Comment by SENya1990** [comment]
Hi @biggik . Can you please share with us more info about your system?
What version of Acuminator and Visual Studio do you use?
Do you use the latest update of Visual Studio?

**Comment by biggik** [comment]
Hi there,

These are the versions I'm using

[image: image.png]

[image: image.png]

**Comment by SENya1990** [comment]
@biggik unfortunately nothing is displayed for me. Could you please write versions in text?

**Comment by biggik** [comment]
Sure

Acuminator version 1.6.2
VS Communited 2019 16.1.6

b

**Comment by SENya1990** [comment]
Ok, we will create a bug for this issue in our bugtracking system. This issue will be closed after the fix.

**Comment by SENya1990** [comment]
The issue should be solved by this pull request:
https://github.com/Acumatica/Acuminator/pull/312
